# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flower-client
#   labels:
#     app: flower-client
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: flower-client
#   template:
#     metadata:
#       labels:
#         app: flower-client
#     spec:
#       containers:
#       - name: kubeflower
#         image: kubeflower:latest
#         imagePullPolicy: IfNotPresent
#         command: ["/bin/sh", "-c"]
#         args: ["python ./src/client.py --server 'service-server' --port '30051'"]
#         ports:
#         - containerPort: 30051

# Flower SuperNode with PVC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-client
  labels:
    app: flower-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flower-client
  template:
    metadata:
      labels:
        app: flower-client
    spec:
      containers:
        - name: kubeflower
          image: kubeflower:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["flower-supernode"]
          args:
            - "--insecure"
            - "--superlink=service-server:9092"
          # GPU 資源需求
          resources:
            limits:
              # nvidia.com/gpu: 1
              memory: "8Gi"
              cpu: "4"
            requests:
              # nvidia.com/gpu: 1
              memory: "4Gi"
              cpu: "2"
          env:
            - name: DATA_PATH
              value: "/app/data" # image 裡的 data.csv 在這
            - name: CACHE_DIR
              value: "/app/cache" # PVC 掛這裡
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: flower-cache
              mountPath: /app/cache
      volumes:
        - name: flower-cache
          persistentVolumeClaim:
            claimName: my-pvc
