# apiVersion: v1
# kind: Service
# metadata:
#   name: service-server # 名稱可以維持不變
# spec:
#   selector:
#     app: flower-server # 要跟 Deployment 裡 template.metadata.labels 一致
#   type: ClusterIP
#   ports:
#     - name: fleet
#       port: 9092 # 給 SuperNode 用來連線的 Fleet API
#       targetPort: 9092
#     - name: control
#       port: 9093 # 給 flwr run 用的 Control API（之後用得到）
#       targetPort: 9093

#測試
apiVersion: v1
kind: Service
metadata:
  name: service-server
spec:
  selector:
    app: flower-server
  type: ClusterIP
  ports:
    - name: fleet
      port: 9092 # 叢集內部看到的 port
      targetPort: 9092 # Pod 裡 flower-superlink 聽的 port
    - name: ctrl
      port: 9093
      targetPort: 9093
